apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::903752074010:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::903752074010:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12OKH9RER7ELB
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-27T17:57:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1191"
  uid: 7f4272d3-7011-4da3-a873-290ba64a342e
