apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::903752074010:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::903752074010:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1T6CNXPO709WF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-28T13:06:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1323"
  uid: d7413639-12ef-4209-a2d6-bc9fa1f6b930
